server:
  port: 8082

spring:
  profiles:
    active: default
  application:
    name: consumer-application
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5434/consumerdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/changelog/changelog-master.xml
    drop-first: true
    contexts: sql
    enabled: true


