version: '3.6'
services:
  postgres:
    image: postgres:16-alpine
    container_name: my-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

  zookeeper:
    image: zookeeper:3.6
    container_name: my-zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: bitnami/kafka:3.2.3
    container_name: my-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LOCAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: LOCAL
    depends_on:
      - zookeeper
    restart: always

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: my-kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    restart: always

volumes:
  pgdata: